version: "3"
services:
  miner-test:
    container_name: miner-test
    build: "./miner"
    image: uhub.service.ucloud.cn/hard_docker/pyethapp-miner:0.5
    #image: localethereum/pyethapp-miner
    volumes:
     - /root/docker-pyeth-dev/miner/start-test.sh:/root/start.sh
     - /root/pyethereum:/ethereum/pyethereum
     - /root/pyethapp:/ethereum/pyethapp
    ports:
     - "8545:8545"
    environment:
      - BOOTSTRAP_NODE=enode://d3260a710a752b926bb3328ebe29bfb568e4fb3b4c7ff59450738661113fb21f5efbdf42904c706a9f152275890840345a5bc990745919eeb2dfc2c481d778ee@10.19.126.200:30303
      - MINE_PERCENT=50
      - SLEEPTIME=1
    restart: always
    networks:
      back:
          ipv4_address: 172.18.250.40
networks:
  back:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.18.250.0/24
