version: "3"
services:
  bootstrap:
    container_name: bootstrap
    build: "./bootstrap"
    image: localethereum/pyethapp-bootstrap
    volumes:
     - /root/docker-pyeth-dev/bootstrap/start-boot.sh:/root/start.sh
     - /root/pyethereum:/ethereum/pyethereum
     - /root/pyethapp:/ethereum/pyethapp
     - /root/pydevp2p:/ethereum/pydevp2p
     - /root/docker-pyeth-dev/bootstrap/data/config:/root/.config/pyethapp
    restart: always
    ports:
     - "40303:40303/tcp"
     - "40303:40303/udp"
     - "18545:18545"
    networks:
      back:
          ipv4_address: 172.18.250.2
networks:
  back: 
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config: 
      - subnet: 172.18.250.0/24
